[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "podman-hpc-py"
dynamic = ['version']
dependencies = [
  "podman-hpc @ git+https://github.com/cjh1/podman-hpc@d01773a8ae14489af7654d799d9738a2c5629248",
  "pyyaml",
  "podman==5.4.0.1"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

requires-python = ">=3.8"
authors = [
  { name="Chris Harris", email="cjh@lbl.gov" },
]
description = "Python bindings for Podman HPC RESTful API"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
  "pytest"
]