[project]
name = "podman-hpc-client"
version = "0.1.0"
description = "Python bindings for Podman HPC RESTful API"
readme = "README.md"
authors = [
  { name="Chris Harris", email="cjh@lbl.gov" },
]
requires-python = ">=3.9"
dependencies = [
    "podman==5.4.0.1",
    "podman-hpc",
    "pyyaml>=6.0.3",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
podman-hpc = { git = "https://github.com/cjh1/podman-hpc", rev = "d01773a8ae14489af7654d799d9738a2c5629248" }

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
